# Generated by Django 5.1.1 on 2024-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_clients',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_leads',
            field=models.IntegerField(default=5),
        ),
    ]
