# Generated by Django 5.1.1 on 2024-10-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_plan_max_clients_alter_plan_max_leads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_clients',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_leads',
        ),
    ]
