# -*- coding: utf-8 -*-
"""03/07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKINGvLLtDOhXXnPap8ym1VHQpHUMQtC
"""

l = ['Akash','Bhargav','chetan']
print(l[2][1])
rev=[]
list = [1,212,34,83,927,908]
for i in range(len(list)-1,-1,-1):
    rev.append(list[i])
print(rev)
print(list)