# -*- coding: utf-8 -*-
"""05/07 Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUh5HuGD6nqg__DCy6KLDAN8L07IMVb7
"""

total_candies_to_load = int(input("how many candies to be loaded on to the vending machine?"))
print("🍬🍬Candy Vending Machine🍬🍬")
print(f"Total no. of candies loaded: {total_candies_to_load}")
numberOfCandiesUserWants = int(input("Enter the no. of candies you want: "))
if numberOfCandiesUserWants <=0 or numberOfCandiesUserWants>total_candies_to_load:
  print("You have entered number of candies which is either zero or less than zero and is not possible to disperse please try again or visit once again Thanks for shopping with us!!! we will be happy to serve you once again")
else:
  cost_of_candy = 1
  total_cost = numberOfCandiesUserWants * cost_of_candy
  print(total_cost)
  UserMoney = int(input("Enter the amount you are paying: "))
  if UserMoney == total_cost:
    for i in range(numberOfCandiesUserWants):
      print("Delivering")

    total_candies_to_load = total_candies_to_load - numberOfCandiesUserWants
    print(f"Number of candies left: {total_candies_to_load}")
    print("Thank You")
  else:
    print("Enter wrong amount. Try again !")

n = int(input("Enter the range upto which you want to print the odd and even nos: "))
even=[]
odd=[]
for i in range(11,n):
  if i%2==0:
    even.append(i)
  else:
    odd.append(i)
print("List of even numbers within given range: ",even)
print("List of even numbers within given range: ",odd)

sentence = input("Enter a sentence: ")
upper_letters = 0
lower_letters = 0
digits =0
symbols = 0
for i in sentence:
  if i.isupper():
    upper_letters+=1
  elif i.islower():
    lower_letters+=1
  elif i.isdigit():
    digits+=1
  else:
    symbols+=1

print("Number of upper case letters: ",upper_letters)
print("Number of lower case letters: ",lower_letters)
print("Number of digits: ",digits)
print("Number of symbols: ",symbols)

user_name = input("Enter user name: ")
password = input("Enter password: ")
if password.isalpha():
  print("Validation Successful.Given password is ok.")
else:
  print("Validation Failed.Given password is not ok.")

y = int(input("Enter the year: "))
if y%4==0:
  if y%100==0:
    if y%400==0:
      print("Leap Year")
    else:
      print("Not a Leap Year")
  else:
    print("Leap year")
else:
  print("Not a Leap Year")