# -*- coding: utf-8 -*-
"""11/06Classwork

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjQFftuJddxGH0b_X-c2QHBn92g9JssW
"""

print("Press 1 for Withdraw.")
print("Press 2 for Deposit Cash.")
print("Press 3 for Balance Enquiry.")
print("Press 4 for Fast Cash.")
bank_balance = 50000
user_input = int(input("Enter your choice: "))
if user_input == 1:
  withdraw_amount = int(input("Enter the amount you want to withdraw: "))
  if withdraw_amount % 100 == 0 and withdraw_amount<=bank_balance:
    print("Amount Withdrawn")
  else:
    print("Please Enter correct amount.")
elif user_input == 2:
  deposit_amount = int(input("Enter the amount you wnat to deposit: "))
  bank_balance = bank_balance + deposit_amount
  print("Amount Deposited")
elif user_input == 3:
  print("Your Balance is: ", bank_balance)
elif user_input == 4:
  print("For Fast Cash. Select any of the following options: \n5000\n10,000\n20,000\n25,000\n30,000\n40,000\n45,000\50,000")
  fast_cash = [5000, 10000, 20000, 25000, 30000, 40000, 45000, 50000]
  fast_cash_amount = int(input("Enter the amount you want to withdraw: "))
  if fast_cash_amount in fast_cash and fast_cash_amount<=bank_balance:
    print("Amount Withdrawn")
  else:
    print("Please Enter correct amount.")
else:
  print("Invalid Input")

num1= int(input("Enter first no.: "))
num2= int(input("Enter second no.: "))
num3= int(input("Enter third no.: "))
if num1==num2==num3:
  print("All numbers are equal")
else:
  if num1>num2 and num1>num3:
    print("num1 is greatest")
  elif num2>num1 and num2>num3:
    print("num2 is greatest")
  else:
    print("num3 is greatest")
  if num1<num2 and num1<num3:
    print("num1 is smallest")
  elif num2<num1 and num2<num3:
    print("num2 is smallest")
  else:
    print("num3 is smallest")