# -*- coding: utf-8 -*-
"""13/06 forloop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAqx67odfdnarf2xaqjim57EtLlp7h9n
"""

string = "abcdefghijklmnopqrstuvwxyz"
for i in string:
    print(i.upper(),end=',')

