# -*- coding: utf-8 -*-
"""14/06 Classtest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjrFEtEyV0c5vr4E_aERAZEQISIfWbzG

The RTO (Regional Transport Office) website holds a registration form which is responsible for registering a user for a Driving License. The RTO wants to take the next step if and only if the user's age is greater than or equal to 18.

Scenario 1 : When Traffic Light is Red

Jake, a 20 year old teenager has learnt to ride a bike and is a bit confused with the traffic signals. He doesn't know what to do when the signal is red.

So In this scenario Jake should just know what Jake should do when the signal is red whether he should leave or stop.

So Write a If-Else condition to guide Jake
"""

age=20
traffic_light="red"


if age>=18:
  if traffic_light == "red":
    print("STOP")
  else:
    print("GO")
else:
  print("Not eligible for driving license")

"""Mary, a 15 year old girl, was watching her mom making a budget list every month, either her mom use to forget few things or she use to go out of budget due to no proper grocery list that says quantity of items, prices and stuff.

So Mary wants to help her mom in managing the monthly groceries by creating an app that takes grocery item name, item price and quantity of item.

Before all this, the app is suppose to accept the budget amount, if shopping list items price cross over the budget amount then any new items should not be added to the list.

There should be 2 things in the menu of the app one to add an item and the second option to exit from the menu once the add item is chosen, then the item name, item quantity and item price should be accepted and the price should be checked with the budget amount. If the item amount is crossing the budget amount then the item cannot be added to the list.

If the exit option is chosen then the total budget amount and the total one
"""

budget=float(input("enter your budget: "))
current_total = 0
items =[]
running=True
while running:
  print("\nMENU")
  print("1. Add Item")
  print("2. Exit")
  choice = int(input("Enter your choice: "))
  if choice == 1:
    item_name = input("Enter the item name: ")
    item_price = float(input("Enter the item price: "))
    item_quantity = int(input("Enter the item quantity: "))
    total_price = item_price * item_quantity
    if current_total + total_price <= budget:
      items.append((item_name, item_quantity, item_price))
      current_total += total_price
      print("Item added to the list.")
    else:
      print("Budget exceeded. Item cannot be addedto the list.")
  elif choice == 2:
    print("GROCERY LISTS")
    for item, quantity, price in items:
      print(f"{item}: {quantity} x ₹{price} = ₹{quantity * price}")
      print(f"Total cost: ₹{current_total}")
      print(f"Remaining Budget: ₹{budget - current_total}")
    running = False
  else:
    print("Invalid choice. Please try again.")

"""Sameer, a resident of India met John, a resident of california on facebook and they became friends, just in a conversation they planned to know each other's height and there was a problem, John would understand only if told in centimeter(cm) format. So write a program to help John to understand Sameer’s height in python to convert Feet & Inches To CM"""

cmperinch = 2.54
inchesperfoot = 12

height_in_feet = int(input("Enter your height in feet: "))
height_in_inches = int(input("Enter your height in inches: "))
total_inches = height_in_feet * inchesperfoot + height_in_inches
height_in_cm = total_inches * cmperinch
print("Your height in centimeters is: ",height_in_cm,"CM")