# -*- coding: utf-8 -*-
"""Assingment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_ZGsOH5RrgEzFoYm9bShEbTXWdRxaH6
"""

print("Arvind")
print("Name: Samanwaya")
print("Age: 23")

print("Square:")
print(" -------")
print("|       |")
print("|       |")
print(" -------")

print("Triangle:")
print("  /\  ")
print(" /  \ ")
print("/____\ ")

print("Rectangle:")
print("-----")
print("|   |")
print("|   |")
print("-----")

print("Sahil \nArvind \nNidhi \nHimanshu \nShubh")

name = str(input("Enter you name: "))
age = int(input("Enter your age: "))
grade = int(input("Enter your grade: "))
address = input("Enter your address: ")
print(f'''My name is {name}. I am {age} years old and currently studying in grade {grade}.
I live at {address}.''')

print("Hi, I am a chatbot. What is your name?")
name = input(">> ")
print(f"Oh, {name}, in which grade you are right now?")
grade = input(">> ")
print(f"{name}, you are in {grade}th grade. Can I ask you one question? yes or no?")
response = input(">> ")
print("Tell me 1024 + 98 = ?")
answer = input(">> ")
print("Good! Your answer is correct. Bye")
greet=input()

count = int(input("Enter the no. of books to buy: "))
amount = count*2
print("The amount to be paid is:",amount,"$")

a = int(input("Enter first no.: "))
b = int(input("Enter second no.: "))
print("Addition of a and b: ",a+b)
print("Subtraction of a and b: ",a-b)
print("Multiplication of a and b: ",a*b)
print("Division of a and b: ",a/b)

birth_year = int(input("Enter your year of birth: "))
age = 2024 - birth_year
print("Your age is: ",age)