# -*- coding: utf-8 -*-
"""Assignment2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyNy2pZDcggnhlBpKd-dCvU-Q2qkPDLE
"""

Total_chocolates = 327
Total_students = 78
chocolate_remaining_after_equal_diste_rem = 327%78
print("The no. of chocolates remaining after equal distribution to 78 students: ",chocolate_remaining_after_equal_diste_rem)

customerName = input("Enter your name: ")
customerMobileNumber = input("Enter your mobile number: ")
customerAge = input("Enter your age: ")
customerEmailId = input("Enter your email ID: ")

print(f'''Hi, {customerName}!!\nThanks for visiting our restaurant and registering for our lucky draw competition on our 25th Anniversary.\nOnce the lucky draw results are announced you will receive a message on your mobile number : {customerMobileNumber}.\nAn detailed description of your gift on your email Id : {customerEmailId}.\nThank you for being a valued customer,{customerName}!!\n"Dominos"''')

Total_students = 60
Number_of_students_per_team =4
total_number_of_teams = 60//4 #can be done with '/' operator also. But used '//' operator to cut off the decimal part.
print("Total no of teams created ",total_number_of_teams)

fahrenheit_temperature = float(input("Enter temperature in Fahrenheit: "))
celsius = (fahrenheit_temperature - 32) * 5.0/9.0
print("The celsius equivalent to given farenheit temperature is: ",celsius,"°C")