# -*- coding: utf-8 -*-
"""functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrLY5LtQAghEXdIRpq4oF0NcR_-R0srZ

Write a Python program to detect the number of local variables declared in a function.


write a python program of finding prime numbers


write a python program of creating chatbot major one using functions
"""

def Prime(x):
  for i in range(2,x):
    if x%i==0:
      return False
    else:
      return True

print(Prime(23))

#using recursion
def isPrime(x,i=2):
  if x==i:
    return True
  elif x%i==0:
    return False
  return isPrime(x,i+1)

print(isPrime(23))

def count_local_variables():

def chatbot():
  questions = ["How are you?", "What's your name?", "How old are you?","What do you stay?"]
  print("Hello! I'm a Chatbot")
  running = True
  while running:
    user_input = input("You: ")
    if user_input.lower() == "bye":
      print("Chatbot: Goodbye!")
      break
    else:
      for i in questions:
        print(i)
        user_input = input("You: ")

chatbot()

def calculator(n,a,b):
   n = input("Enter the operator: ")
   a= int(input("Enter the first number: "))
   b= int(input("Enter the second number: "))
   if n == "+":
      print(a+b)
   elif n == "-":
      print(a-b)
   elif n == "*":
      print(a*b)
   elif n == "/":
      print(a/b)
   else:
      print("Invalid operator")
calculator(n,a,b)

def isEvenorOdd(n):
   if n%2 == 0:
      print("Even")
   else:
      print("Odd")
isEvenorOdd(n)

def quiz():
  questions = {
      "What is 1 + 1?": "2",
      "What is the capital of France?": "Paris",
      "Capital of India": "Delhi",
      "What is the largest planet in our solar system?": "Jupiter",
      "Which planet is closest to the sun?": "Mercury"
      "National Bird of India": "Peacock"
  }
  for q in question.items():
    if

if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    coordinates = [[i for i in range(x+1), j for j in range(y+1), k for k in range(z+1) if i+j+k!=n]]
    print(coordinates)